name: iOS-ipa-build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    name: "🎉 iOS Build"
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install iOS dependencies (CocoaPods)
        run: pod install --repo-update
        working-directory: ios
        
      - name: Build iOS App (without CastarSDK)
        run: flutter build ios --release --no-codesign
        env:
          FLUTTER_BUILD_NUMBER: ${{ github.run_number }}

      - name: Post-Build CastarSDK Integration
        run: |
          cd ios
          chmod +x post_build_integrate.sh
          ./post_build_integrate.sh
        working-directory: ios

      - name: Prepare IPA for release
        run: |
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -qq -r -9 FlutterIpaExport.ipa Payload
        
      - name: Generate Release Tag
        id: tag
        run: echo "tag=v$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body: |
            ## ✨ New iOS Build with Post-Build CastarSDK Integration
            This release contains the latest iOS build with CastarSDK integrated after build.
            
            **Features:**
            - Modern Material Design 3 UI
            - CastarSDK integration (post-build)
            - Client ID input with validation
            
            **Build Info:**
            - **Tag:** `${{ steps.tag.outputs.tag }}`
            - **Date:** `$(date)`
            - **Flutter Version:** `stable`
            - **Integration Method:** Post-build script
          draft: false
          prerelease: false

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: FlutterIpaExport.ipa
          asset_content_type: application/octet-stream 