name: iOS-ipa-build

on:
  push:
  workflow_dispatch:

jobs:
  build-ios:
    name: "🎉 iOS Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      
      - run: pod repo update
        working-directory: ios

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Generate Release Tag
        id: tag
        run: echo "tag=v$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body: |
            This is a release of the CastarSDK Flutter app.
            
            ## Features
            - Modern Material Design 3 UI
            - CastarSDK integration for monetization (framework linking in progress)
            - Client ID input with validation
            - Success feedback and notifications
            - iOS IPA build
            
            ## Build Info
            - Build Date: $(date)
            - Flutter Version: stable
            - iOS Target: 12.0+
          draft: false
          prerelease: false

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: FlutterIpaExport.ipa
          asset_content_type: application/octet-stream 